# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Apply to all files without commiting:
#   pre-commit run --all-files
# Apply to a single without commiting:
#   pre-commit run --files [file]
# Update this file:
#   pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*
    -   id: trailing-whitespace
        exclude: ^tests/.*/fixtures/.*
    -   id: mixed-line-ending
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
        exclude: ^docs/.*
        args: [--ignore-missing-imports]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args:
            - -m3
            - -tc
            - -w88
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args:
            - --line-length=100

# -   repo: https://github.com/asottile/pyupgrade
#     rev: v2.31.0
#     hooks:
#     -   id: pyupgrade
#         args: [--py36-plus]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
-   repo: local
    hooks:
    -   id: pylint
        name: PyLint
        entry: pylint
        language: python
        files: \.py$
        args:
            - --good-names=i,j,k,x,y,df,a,b,e,N,Wn,X,fp,ax,lr,db,hr,n
            - --max-line-length=100
            # disable:
            # R0903 Too few public methods
            # R0913 Too many arguments (n/5)
            # E0401 Unable to import
            # C0116 missing-function-docstring
            - --disable=R0903, R0913, E0401, C0116
